name: Run tests on develop

on:
  push:
    branches:
    - develop
    paths:
    - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100

    - name: Test with dotnet
      working-directory: ./src
      run: dotnet test