name: .NET Core

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
        
    - name: Build with dotnet
      env: 
        BUILD_NUMBER: git rev-list --count HEAD
      run: dotnet pack --configuration Release -o out /p:Version=1.0.0.$BUILD_NUMBER
      
    - name: Push nuget package
      run: dotnet nuget push ./out/*.nupkg -k ${{ secrets.Nuget_Key }} -s https://api.nuget.org/v3/index.json
